version: "3.8"
services:
  server:
    build:
      context: ..
      dockerfile: deployment/dockerfiles/server.Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../tmp:/app/tmp     # if you want host temp folder
    depends_on: []
